import { useEffect, useState } from 'react'
import { Icon } from '@iconify/react'
import sparkleIcon from '@iconify/icons-mdi/creation'
import refreshIcon from '@iconify/icons-mdi/refresh'
import { fetchAiBriefing } from '../utils/aiBriefing'

const AiBriefing = ({wildfires}) => {
    const [status, setStatus] = useState('idle')
    const [text, setText] = useState('')

    const generate = async () => {
        setStatus('loading')
        try {
            const briefing = await fetchAiBriefing(wildfires)
            setText(briefing)
            setStatus('ready')
        } catch (err) {
            setText(
                err.message === 'MISSING_API_KEY'
                    ? 'Add REACT_APP_ANTHROPIC_API_KEY to your .env file to enable AI briefings.'
                    : 'Could not generate a briefing right now.'
            )
            setStatus('error')
            console.error('AI briefing failed:', err)
        }
    }

    useEffect(() => {
        if (wildfires.length > 0 && status === 'idle') {
            generate()
        }
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [wildfires.length])

    return (
        <div className="ai-briefing">
            <div className="ai-briefing-header">
                <span className="ai-briefing-title">
                    <Icon icon={sparkleIcon} /> AI Risk Briefing
                </span>
                <button
                    className="ai-briefing-refresh"
                    onClick={generate}
                    disabled={status === 'loading' || wildfires.length === 0}
                    aria-label="Regenerate briefing"
                >
                    <Icon icon={refreshIcon} className={status === 'loading' ? 'spin' : ''} />
                </button>
            </div>
            <p className={`ai-briefing-body ${status === 'error' ? 'error' : ''}`}>
                {status === 'loading' ? 'Analyzing current wildfire activity...' : text}
            </p>
            {status === 'ready' && <span className="ai-briefing-caption">Generated by Claude</span>}
        </div>
    )
}

export default AiBriefing
